# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Our blog'
description: 'This is our new blog'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=136"

# Pagination
paginate: 10
paginate_path: page:num

# Collections
collections:
  posts:
    title: Blog - Xdddd
    output: true
    description: "The blogs here!"
